### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by gaoryrt** [fanpei91/fanpei91.github.io#1]
https://fanpei91.com/posts/implement-double-proxies-to-cross-firewall-by-using-https/ 中「特则提取」应为「特征提取」。

**Comment by gaoryrt** [comment]
https://github.com/fanpei91/fanpei91.github.io/blob/0f095b551331d6e59a7fd731aa9ce01f3de8a50b/posts/implement-double-proxies-to-cross-firewall-by-using-https/index.html#L42

**Comment by fanpei91** [comment]
谢谢指出！想不到居然有人看我这破小博客。

**Comment by gaoryrt** [comment]
issue 这边可以被用作您不想有的评论区，蛮搞笑的

**Comment by fanpei91** [comment]
但依然阻挡不了有心人。：）
